create table if not exists book (
  asin varchar not null,
  isbn varchar,
  answered_questions int,
  availability varchar,
  brand varchar,
  currency varchar,
  date_first_available date,
  delivery varchar[],
  description varchar,
  discount decimal,
  domain varchar,
  features varchar[],
  final_price decimal,
  formats jsonb,
  image_url varchar,
  images_count int,
  initial_price decimal,
  item_weight varchar,
  manufacturer varchar,
  model_number varchar,
  plus_content boolean,
  product_dimensions varchar,
  rating varchar,
  reviews_count int,
  root_bs_rank int,
  seller_id varchar,
  seller_name varchar,
  timestamp timestamptz,
  title varchar,
  url varchar,
  video boolean,
  video_count int,
  categories varchar[],
  best_sellers_rank jsonb,
  primary key (asin)
);